### PR TITLE
Fixing css icon size

### LINKED ISSUE #1222: Icon sizes changed after 5.x update
### Describe the bug

Before updating to AppUI 5.x in Pineapple toolbar icons were 16x16 but after upgrading these icons now differ in size. Some are 14x14 and some are 16x16.

### Expected Behavior

Icons should be consistent size (16x16).

### Screenshots

Before 5.x upgrade:

Image

After 5.x upgrade:

Image

### Desktop (please complete the applicable information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by linasgeg**
## Changes

Closes #1222

Added styling to CSS icons used by the `IconComponent` to match size of SVG icons

image

Actual icons are sometimes bigger than 16x16, but this was also the case in AppUI v4

image image

### CODE REVIEW

File: ui/core-react/src/core-react/icons/IconComponent.tsx [hunk 1]
```diff
@@ -97,7 +97,12 @@ export function Icon(props: IconProps) {
     // CSS icon
     return (
       <i
-        className={classnames("icon", iconString, props.className)}
+        className={classnames(
+          "icon",
+          "core-css-icon",
```
Comment (GerardasB) [inline ui/core-react/src/core-react/icons/IconComponent.tsx:102]: Should we revert all changes to `Item.tsx` and handle this in `IconComponent.tsx` and related `scss` file?
The only downside to this is that we might "unintentionally" change the size of `Icon` used in other components, however that shouldn't be an issue, since `iconSpec` is rendered inconsistently either way: 16px `svg` vs 14px `web font icon`.

Comment (linasgeg) [reply ui/core-react/src/core-react/icons/IconComponent.tsx:102]: Reverted. Also removed `core-menuitem-icon` from `ItemComponent.scss`, because it is no longer used.

**Review by GerardasB — APPROVED** [review]

**Comment by linasgeg** [comment]
@Mergifyio backport release/5.3.x
