### PR TITLE
Fix `UiFramework.frontstages.onWidgetStateChangedEvent` event to correctly emit widget state changes

### LINKED ISSUE #757: UiFramework.frontstages.onWidgetStateChangedEvent is not being fired when widget state is changed from floating to open
### Describe the bug

When widget state changes from `WidgetState.Floating` directly o `WidgetState.Open`, UiFramework.frontstages.onWidgetStateChangedEvent is not being fired.

### To Reproduce

1. Go to a frontstage and move any widget to floating state, while keeping it open.
2. Set everything up in such a way that after clicking "Send to panel" button the widget will be sent to panel but will remain open in the panel.
3. Click "Send to panel" button.

### Expected Behavior

Widget state changes from `WidgetState.Floating` to `WidgetState.Open` and UiFramework.frontstages.onWidgetStateChangedEvent IS fired.

### Desktop

- OS: Windows 11
- Browser: electron 25.8.1
- iTwin.js AppUI Version: 4.10.0
- iTwin.js Version: 4.4.3

### PR DESCRIPTION
**Pull request by GerardasB**
## Changes

Fixes #757 
`UiFramework.frontstages.onWidgetStateChangedEvent` event will now correctly emit widget state changes.
Values emitted by the event will match `WidgetState` returned by `WidgetDef.state`.

## Testing

Added additional unit tests.

Tested via standalone test-app:
- Open <http://localhost:3000/?frontstage=appui-test-providers:WidgetApi>
- Open `Layout Info` widget
- Select a widget to inspect i.e. `FW-1`
- Interact with `FW-1` widget, note how `state={WidgetState}` output changes

### CODE REVIEW

File: ui/appui-react/src/appui-react/widgets/WidgetDef.tsx [hunk 1]
```diff
@@ -103,12 +106,10 @@ export class WidgetDef {
 
   public get state(): WidgetState {
     const frontstageDef = UiFramework.frontstages.activeFrontstageDef;
-    if (frontstageDef && frontstageDef.findWidgetDef(this.id)) {
-      const currentState = frontstageDef.getWidgetCurrentState(this);
-      // istanbul ignore else
-      if (undefined !== currentState) return currentState;
-    }
-    return this.defaultState;
+    const state = frontstageDef?.nineZoneState;
```
Comment (ignas-k) [inline ui/appui-react/src/appui-react/widgets/WidgetDef.tsx:109]: The name `state` seems a bit generic here since the property method is already called `state` and we also pass `state` to `getWidgetState` function.

File: ui/appui-react/src/appui-react/widgets/WidgetDef.tsx [hunk 2]
```diff
@@ -578,3 +579,44 @@ export class WidgetDef {
     });
   }
 }
+
+/** @internal */
+export function getWidgetState(widgetDef: WidgetDef, state: NineZoneState) {
```
Comment (ignas-k) [inline ui/appui-react/src/appui-react/widgets/WidgetDef.tsx:584]: Is there a reason you want this to be exported as a separate method? It seems that it fits perfectly inside `WidgetDef` class since we need to pass an object of that type anyway.

File: ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx [hunk 3]
```diff
@@ -187,35 +183,96 @@ describe("FrontstageDef", () => {
...
-        sections: {
-          start: [
-            {
-              id: "test-widget",
-              defaultState: WidgetState.Hidden,
-            },
-          ],
+  describe("onWidgetStateChangedEvent", () => {
+    it("should open a hidden widget", async () => {
+      const def = new FrontstageDef();
```
Comment (ignas-k) [inline ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx:188]: nitpick: maybe let's use a name that is more specific e.g. `frontstageDef`. Same applies to tests below.

**Review by ignas-k — CHANGES_REQUESTED** [review]

File: ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx (hunk 3 above)
Comment (GerardasB) [reply ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx]: Renamed.

File: ui/appui-react/src/appui-react/widgets/WidgetDef.tsx (hunk 1 above)
Comment (GerardasB) [reply ui/appui-react/src/appui-react/widgets/WidgetDef.tsx:109]: Renamed to `nineZone`.

File: ui/appui-react/src/appui-react/widgets/WidgetDef.tsx (hunk 2 above)
Comment (GerardasB) [reply ui/appui-react/src/appui-react/widgets/WidgetDef.tsx]: With #766 this way we might keep the API a bit cleaner. Long term our strategy should be aimed at deprecating these classes..

File: ui/appui-react/src/appui-react/widgets/WidgetDef.tsx (hunk 1 above)
Comment (ignas-k) [reply ui/appui-react/src/appui-react/widgets/WidgetDef.tsx:109]: I see you changed it in `getWidgetState` but it would be good to change it here as well.

Comment (GerardasB) [reply ui/appui-react/src/appui-react/widgets/WidgetDef.tsx]: Renamed.
